export const dna = 
`
ruler_designer_542719970={
	type=female
	id=0
	genes={ 		
		hair_color={ 160 130 160 130 }
 		skin_color={ 105 155 105 155 }
 		eye_color={ 235 40 235 40 }
 		gene_chin_forward={ "chin_forward_pos" 140 "chin_forward_pos" 140 }
 		gene_chin_height={ "chin_height_neg" 145 "chin_height_neg" 145 }
 		gene_chin_width={ "chin_width_pos" 150 "chin_width_pos" 150 }
 		gene_eye_angle={ "eye_angle_neg" 100 "eye_angle_neg" 100 }
 		gene_eye_depth={ "eye_depth_pos" 165 "eye_depth_pos" 165 }
 		gene_eye_height={ "eye_height_neg" 110 "eye_height_neg" 110 }
 		gene_eye_distance={ "eye_distance_neg" 130 "eye_distance_neg" 130 }
 		gene_eye_shut={ "eye_shut_pos" 125 "eye_shut_pos" 125 }
 		gene_forehead_angle={ "forehead_angle_neg" 160 "forehead_angle_neg" 160 }
 		gene_forehead_brow_height={ "forehead_brow_height_pos" 125 "forehead_brow_height_pos" 125 }
 		gene_forehead_roundness={ "forehead_roundness_pos" 135 "forehead_roundness_pos" 135 }
 		gene_forehead_width={ "forehead_width_neg" 110 "forehead_width_neg" 110 }
 		gene_forehead_height={ "forehead_height_pos" 110 "forehead_height_pos" 110 }
 		gene_head_height={ "head_height_pos" 155 "head_height_pos" 155 }
 		gene_head_width={ "head_width_pos" 125 "head_width_pos" 125 }
 		gene_head_profile={ "head_profile_pos" 85 "head_profile_pos" 85 }
 		gene_head_top_height={ "head_top_height_pos" 165 "head_top_height_pos" 165 }
 		gene_head_top_width={ "head_top_width_pos" 165 "head_top_width_pos" 165 }
 		gene_jaw_angle={ "jaw_angle_neg" 140 "jaw_angle_neg" 140 }
 		gene_jaw_forward={ "jaw_forward_pos" 135 "jaw_forward_pos" 135 }
 		gene_jaw_height={ "jaw_height_pos" 180 "jaw_height_pos" 180 }
 		gene_jaw_width={ "jaw_width_neg" 145 "jaw_width_neg" 145 }
 		gene_mouth_corner_depth={ "mouth_corner_depth_pos" 145 "mouth_corner_depth_pos" 145 }
 		gene_mouth_corner_height={ "mouth_corner_height_pos" 140 "mouth_corner_height_pos" 140 }
 		gene_mouth_forward={ "mouth_forward_pos" 135 "mouth_forward_pos" 135 }
 		gene_mouth_height={ "mouth_height_pos" 35 "mouth_height_pos" 35 }
 		gene_mouth_width={ "mouth_width_pos" 120 "mouth_width_pos" 120 }
 		gene_mouth_upper_lip_size={ "mouth_upper_lip_size_neg" 115 "mouth_upper_lip_size_neg" 115 }
 		gene_mouth_lower_lip_size={ "mouth_lower_lip_size_neg" 180 "mouth_lower_lip_size_neg" 180 }
 		gene_mouth_open={ "mouth_open_neg" 120 "mouth_open_neg" 120 }
 		gene_neck_length={ "neck_length_neg" 135 "neck_length_neg" 135 }
 		gene_neck_width={ "neck_width_pos" 100 "neck_width_pos" 100 }
 		gene_bs_cheek_forward={ "cheek_forward_pos" 60 "cheek_forward_pos" 60 }
 		gene_bs_cheek_height={ "cheek_height_neg" 30 "cheek_height_neg" 30 }
 		gene_bs_cheek_width={ "cheek_width_neg" 15 "cheek_width_neg" 15 }
 		gene_bs_ear_angle={ "ear_angle_pos" 50 "ear_angle_pos" 50 }
 		gene_bs_ear_inner_shape={ "ear_inner_shape_pos" 95 "ear_inner_shape_pos" 95 }
 		gene_bs_ear_bend={ "ear_lower_bend_pos" 80 "ear_lower_bend_pos" 80 }
 		gene_bs_ear_outward={ "ear_outward_pos" 75 "ear_outward_pos" 75 }
 		gene_bs_ear_size={ "ear_size_pos" 75 "ear_size_pos" 75 }
 		gene_bs_eye_corner_depth={ "eye_corner_depth_neg" 35 "eye_corner_depth_neg" 35 }
 		gene_bs_eye_fold_shape={ "eye_fold_shape_pos" 80 "eye_fold_shape_neg" 80 }
 		gene_bs_eye_size={ "eye_size_pos" 50 "eye_size_pos" 50 }
 		gene_bs_eye_upper_lid_size={ "eye_upper_lid_size_pos" 110 "eye_upper_lid_size_pos" 110 }
 		gene_bs_forehead_brow_curve={ "forehead_brow_curve_neg" 120 "forehead_brow_curve_neg" 120 }
 		gene_bs_forehead_brow_forward={ "forehead_brow_forward_pos" 60 "forehead_brow_forward_pos" 60 }
 		gene_bs_forehead_brow_inner_height={ "forehead_brow_inner_height_pos" 5 "forehead_brow_inner_height_pos" 5 }
 		gene_bs_forehead_brow_outer_height={ "forehead_brow_outer_height_neg" 15 "forehead_brow_outer_height_neg" 15 }
 		gene_bs_forehead_brow_width={ "forehead_brow_width_pos" 185 "forehead_brow_width_pos" 185 }
 		gene_bs_jaw_def={ "jaw_def_pos" 40 "jaw_def_pos" 40 }
 		gene_bs_mouth_lower_lip_def={ "mouth_lower_lip_def_pos" 15 "mouth_lower_lip_def_pos" 15 }
 		gene_bs_mouth_lower_lip_full={ "mouth_lower_lip_full_pos" 20 "mouth_lower_lip_full_pos" 20 }
 		gene_bs_mouth_lower_lip_pad={ "mouth_lower_lip_pad_pos" 55 "mouth_lower_lip_pad_pos" 55 }
 		gene_bs_mouth_lower_lip_width={ "mouth_lower_lip_width_pos" 180 "mouth_lower_lip_width_pos" 180 }
 		gene_bs_mouth_philtrum_def={ "mouth_philtrum_def_pos" 55 "mouth_philtrum_def_pos" 55 }
 		gene_bs_mouth_philtrum_shape={ "mouth_philtrum_shape_pos" 5 "mouth_philtrum_shape_pos" 5 }
 		gene_bs_mouth_philtrum_width={ "mouth_philtrum_width_pos" 5 "mouth_philtrum_width_pos" 5 }
 		gene_bs_mouth_upper_lip_def={ "mouth_upper_lip_def_pos" 85 "mouth_upper_lip_def_pos" 85 }
 		gene_bs_mouth_upper_lip_full={ "mouth_upper_lip_full_pos" 70 "mouth_upper_lip_full_pos" 70 }
 		gene_bs_mouth_upper_lip_profile={ "mouth_upper_lip_profile_neg" 210 "mouth_upper_lip_profile_neg" 210 }
 		gene_bs_mouth_upper_lip_width={ "mouth_upper_lip_width_pos" 255 "mouth_upper_lip_width_pos" 255 }
 		gene_bs_nose_forward={ "nose_forward_pos" 30 "nose_forward_pos" 30 }
 		gene_bs_nose_height={ "nose_height_neg" 80 "nose_height_neg" 80 }
 		gene_bs_nose_length={ "nose_length_neg" 20 "nose_length_neg" 20 }
 		gene_bs_nose_nostril_height={ "nose_nostril_height_pos" 0 "nose_nostril_height_pos" 0 }
 		gene_bs_nose_nostril_width={ "nose_nostril_width_neg" 45 "nose_nostril_width_neg" 45 }
 		gene_bs_nose_profile={ "nose_profile_pos" 25 "nose_profile_pos" 25 }
 		gene_bs_nose_ridge_angle={ "nose_ridge_angle_pos" 5 "nose_ridge_angle_pos" 5 }
 		gene_bs_nose_ridge_width={ "nose_ridge_width_neg" 30 "nose_ridge_width_neg" 30 }
 		gene_bs_nose_size={ "nose_size_pos" 25 "nose_size_pos" 25 }
 		gene_bs_nose_tip_angle={ "nose_tip_angle_neg" 135 "nose_tip_angle_neg" 135 }
 		gene_bs_nose_tip_forward={ "nose_tip_forward_pos" 45 "nose_tip_forward_pos" 45 }
 		gene_bs_nose_tip_width={ "nose_tip_width_pos" 50 "nose_tip_width_pos" 50 }
 		face_detail_cheek_def={ "cheek_def_02" 60 "cheek_def_01" 60 }
 		face_detail_cheek_fat={ "cheek_fat_03_pos" 80 "cheek_fat_03_pos" 80 }
 		face_detail_chin_cleft={ "chin_cleft" 0 "chin_cleft" 0 }
 		face_detail_chin_def={ "chin_def" 220 "chin_def" 220 }
 		face_detail_eye_lower_lid_def={ "eye_lower_lid_def" 200 "eye_lower_lid_def" 200 }
 		face_detail_eye_socket={ "eye_socket_color_02" 155 "eye_socket_color_02" 155 }
 		face_detail_nasolabial={ "nasolabial_03" 20 "nasolabial_03" 20 }
 		face_detail_nose_ridge_def={ "nose_ridge_def_neg" 40 "nose_ridge_def_neg" 40 }
 		face_detail_nose_tip_def={ "nose_tip_def" 195 "nose_tip_def" 195 }
 		face_detail_temple_def={ "temple_def" 30 "temple_def" 30 }
 		expression_brow_wrinkles={ "brow_wrinkles_03" 70 "brow_wrinkles_03" 70 }
 		expression_eye_wrinkles={ "eye_wrinkles_01" 40 "eye_wrinkles_01" 40 }
 		expression_forehead_wrinkles={ "forehead_wrinkles_02" 90 "forehead_wrinkles_02" 90 }
 		expression_other={ "cheek_wrinkles_left_01" 135 "cheek_wrinkles_left_01" 135 }
 		complexion={ "complexion_17" 255 "complexion_17" 255 }
 		gene_height={ "normal_height" 125 "normal_height" 125 }
 		gene_bs_body_type={ "body_fat_head_fat_low" 130 "body_fat_head_fat_low" 130 }
 		gene_bs_body_shape={ "body_shape_pear_full" 25 "body_shape_pear_full" 25 }
 		gene_bs_bust={ "bust_shape_3_full" 200 "bust_shape_3_full" 200 }
 		gene_age={ "old_beauty_1" 150 "old_beauty_1" 150 }
 		gene_eyebrows_shape={ "far_spacing_low_thickness" 255 "far_spacing_low_thickness" 255 }
 		gene_eyebrows_fullness={ "layer_2_avg_thickness" 255 "layer_2_avg_thickness" 255 }
 		gene_body_hair={ "body_hair_dense" 200 "body_hair_dense" 200 }
 		gene_hair_type={ "hair_wavy" 190 "hair_wavy" 190 }
 		gene_baldness={ "no_baldness" 150 "no_baldness" 150 }
 		eye_accessory={ "normal_eyes" 25 "normal_eyes" 25 }
 		teeth_accessory={ "normal_teeth" 0 "normal_teeth" 0 }
 		eyelashes_accessory={ "normal_eyelashes" 145 "normal_eyelashes" 145 }
 		skin_color_saturation={ "vanilla_skin_saturation" 125 "vanilla_skin_saturation" 125 }
 		eye_color_saturation={ "vanilla_eye_saturation" 165 "vanilla_eye_saturation" 165 }
 		gene_eye_size={ "eye_size" 115 "eye_size" 115 }
 		gene_eye_shut_top={ "eye_shut_top" 145 "eye_shut_top" 145 }
 		gene_eye_shut_bottom={ "eye_shut_bottom" 110 "eye_shut_bottom" 110 }
 		gene_bs_eye_height_inside={ "eye_height_inside_neg" 150 "eye_height_inside_neg" 150 }
 		gene_bs_eye_height_outisde={ "eye_height_outisde_pos" 85 "eye_height_outisde_pos" 85 }
 		gene_bs_ear_lobe={ "ear_lobe_fused" 60 "ear_lobe_fused" 60 }
 		gene_bs_nose_central_width={ "nose_central_width_pos" 175 "nose_central_width_pos" 175 }
 		gene_bs_nose_septum_width={ "nose_septum_width_pos" 70 "nose_septum_width_pos" 70 }
 		gene_forehead_inner_brow_width={ "vanilla_inner_brow_width" 0 "vanilla_inner_brow_width" 0 }
 		gene_bs_mouth_lower_lip_profile={ "vanilla_lower_lip_profile" 0 "vanilla_lower_lip_profile" 0 }
 		gene_bs_eye_outer_width={ "eye_outer_width" 150 "eye_outer_width" 150 }
 		gene_bs_head_asymmetry_1={ "head_asymmetry_5" 60 "head_asymmetry_5" 60 }
 		gene_bs_eye_fold_2={ "eye_fold_2" 65 "eye_fold_2" 65 }
 		gene_bs_mouth_center_curve={ "mouth_center_curve_max" 35 "mouth_center_curve_max" 35 }
 		gene_bs_eyebrow_straight={ "vanilla_eyebrow_straight" 0 "vanilla_eyebrow_straight" 0 }
 		gene_bs_head_round_shape={ "head_round_shape" 25 "head_round_shape" 25 }
 		gene_bs_nose_septum_height={ "nose_septum_height" 75 "nose_septum_height" 75 }
 		gene_bs_head_lower_height={ "head_lower_height_max" 45 "head_lower_height_max" 45 }
 		gene_bs_nose_flared_nostril={ "vanilla_nose_flared_nostril" 0 "vanilla_nose_flared_nostril" 0 }
 		gene_bs_mouth_upper_lip_forward={ "vanilla_upper_lip_forward" 0 "vanilla_upper_lip_forward" 0 }
 		gene_bs_mouth_lower_lip_forward={ "vanilla_lower_lip_forward" 0 "vanilla_lower_lip_forward" 0 }
 		gene_bs_nose_swollen={ "vanilla_nose_swollen" 0 "vanilla_nose_swollen" 0 }
 		gene_bs_ears_fantasy={ "vanilla_ears_fantasy" 0 "vanilla_ears_fantasy" 0 }
 		gene_bs_mouth_glamour_lips={ "vanilla_mouth_glamour_lips" 0 "vanilla_mouth_glamour_lips" 0 }
 		face_detail_eye_upper_lid_def={ "upper_lid_def" 40 "upper_lid_def" 40 }
 		gene_eyebrow_inner_width={ "eyebrow_inner_width_min" 210 "eyebrow_inner_width_min" 210 }
 		gene_bs_eye_lower_lid_size={ "eye_lower_lid_size" 105 "eye_lower_lid_size" 105 }
 		gene_bs_eye_shape={ "eye_shape_01" 255 "eye_shape_01" 255 }
 		hair_aging={ "vanilla_hair_aging" 0 "vanilla_hair_aging" 0 }
 		gene_body_hair_color={ "body_hair_color" 200 "body_hair_color" 200 }
 		hairstyles={ "all_hairstyles" 235 "all_hairstyles" 0 }
 		beards={ "no_beard" 255 "no_beard" 0 }
 		clothes={ "no_clothes" 255 "most_clothes" 0 }
 	}
	override={
		portrait_modifier_overrides={
			custom_hair=cfp_female_hair_african_02
			custom_beards=female_empty
		}
	}
	entity={ 0 0 }
}`
